# Generated by Django 5.2 on 2025-06-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_shortcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='shortcode',
            new_name='short_code',
        ),
    ]
