# Generated by Django 5.2 on 2025-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_rename_shortcode_url_short_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_code',
            new_name='shortCode',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='original_URL',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='url',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='url',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
