# Generated by Django 5.2 on 2025-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_rename_short_code_url_shortcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
