# Generated by Django 5.2 on 2025-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_url_updatedat_alter_url_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='accessCount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
