# Generated by Django 5.2 on 2025-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_url_accesscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='accessCount',
            field=models.IntegerField(default=0),
        ),
    ]
